### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by si90** [SAP/odfuzz#41]
When trying to run the project via docker I get the following error after a few seconds:

`
odfuzz version: 0.13
Connecting to the database...
Collection: Ccx.svc-df0e18f5-aa3c-4976-a588-3d3f78c107f3
Initializing queryable entities...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1006: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proj.cxxxxxxxx.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "/usr/local/bin/odfuzz", line 11, in <module>
    load_entry_point('odfuzz==0.13', 'console_scripts', 'odfuzz')()
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/odfuzz.py", line 23, in main
    execute(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/odfuzz.py", line 40, in execute
    run_fuzzer(bind, parsed_arguments, collection_name)
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/odfuzz.py", line 82, in run_fuzzer
    manager.start()
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/fuzzer.py", line 56, in start
    entities = self.build_entities()
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/fuzzer.py", line 77, in build_entities
    return builder.build()
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/entities.py", line 52, in build
    data_model = self._get_data_model()
  File "/usr/local/lib/python3.7/dist-packages/odfuzz-0.13-py3.7.egg/odfuzz/entities.py", line 68, in _get_data_model
    service_model = Edmx.parse(metadata_response.content)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 2513, in parse
    return schema_from_xml(metadata_xml, namespaces)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 2506, in schema_from_xml
    return meta.build()
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 2462, in build
    schema = Schema.from_etree(edm_schemas, self._config)
  File "/usr/local/lib/python3.7/dist-packages/pyodata-1.4.0-py3.7.egg/pyodata/v2/model.py", line 991, in from_etree `

**Comment by phanak-sap** [comment]
This is similarly too short stacktrace as in your issue #42. 

All this is about the " InsecureRequestWarning: Unverified HTTPS request is being made to host 'proj.cxxxxxxxx.com'. Adding certificate verification is strongly advised." - it may be only warning and not the actual error that made the fuzzer crash. It may even be the same problem as in #42, just that it cannot be investigated. Use the comment from #42 and please provide more information.

At tha moment, I am considering this as duplicate of #42 unless some new facts proves othervise.

Relevant to the certificate Warning - this part of README may be useful in your case:

> Additional configuration can be set up using following environment variables:
> ...
> ...
> File path where the HTTPS certificate is stored if the service is requiring it.
> 
> export ENV_ODFUZZ_CERTIFICATE_PATH=./cert.crt
>

**Comment by phanak-sap** [comment]
Since no comment from April and the issue is not actionable, closing. Repoen with more data or perhaps the answer resolved the issue.
