### ISSUE TITLE
pin depenencies.

### ISSUE THREAD

**Issue by phanak-sap** [SAP/odfuzz#48]
after pip install - r and pip freeze:

```
gevent==20.5.0
greenlet==0.4.15
lxml==4.5.0
pymongo==3.10.1
pyodata==1.4.0
python-dateutil==2.8.1
PyYAML==5.3.1
```

while currently we have unpinned (and no way to ensure that it works OK in possible combinations)
```
gevent>=1.2.2
requests>=2.18.4
pymongo>=3.6.1
lxml>=3.7.3
pyyaml>=3.13
python-dateutil>=2.7.5
pyodata>=1.3.0
```

 As open question (if yes, then another issue should be created) is necessity of lxml. 
- it is transitive dependency, pyodata depends on it as well. but due python lacks in dependency management, version mismatch can be introduced easily (different requirements for odfuzz in conflict with pyodata requirements).
- if in entities.py is used pyodata, in fuzzer.py should be used as well, or even better just call some new method from entitites.py. The entire lxml relevant code in fuzzer.py should be in my opinion removed (and implemented differently in different place), in respect of better module structure and support for odata v4 in the future.

**Comment by lubosmj** [comment]
The dependencies need to be pinned for sure. Currently, I am experiencing errors while running the fuzzer due to the recent changes made in the gevent API. I am using a fresh and new image built from the master branch. See below the attached snippet to learn more:

```
/odfuzz # odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats -l logs -a
Traceback (most recent call last):
  File "/usr/bin/odfuzz", line 11, in <module>
    load_entry_point('odfuzz==0.13.1', 'console_scripts', 'odfuzz')()
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 23, in main
    execute(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 38, in execute
    set_signal_handler(collection_name)
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 68, in set_signal_handler
    gevent.signal(signal.SIGINT, partial(signal_handler, db_collection_name))
TypeError: 'module' object is not callable
/odfuzz # pip3 freeze
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
gevent==20.5.0
greenlet==0.4.15
idna==2.9
lxml==4.5.0
odfuzz==0.13.1
pycparser==2.20
pymongo==3.10.1
pyodata==1.4.0
python-dateutil==2.8.1
PyYAML==5.3.1
requests==2.23.0
six==1.14.0
urllib3==1.25.9
```

This forced me to create the commit https://github.com/SAP/odfuzz/pull/47/commits/c171d8b288bf4dffeaba9596dc3c88fa55c46097 in order to get rid of the error. We may pin the other dependencies in the similar way as well. In my opinion, we also need to conduct an investigation to find out whether my change affects other parts of the code or not. But it seems like I did not break anything so far.

**Comment by phanak-sap** [comment]
but your commit changed
gevent>=1.2.2 to gevent~=1.5.0 while we both ended with gevent==20.5.0. when installed (since it is the latest). 

But you have difference in 
1) python version, I am on 3.8 and not 3.6
2) the changed line in the PR 47 itself, you deleted `from functools import partial`. Isn't that possible root cause? 

anyway, I would pin it to gevent==20.5.0 directly.

**Comment by phanak-sap** [comment]
I am ABLE TO REPRODUCE the gevent issue with configuration:

Latest HEAD from master c8bfe9e, build docker image, run odfuzz from there:
- requirement.txt containst `gevent>=1.2.2`
- Python 3.6 in the docker image
- Pip grabbedv ` gevent          20.5.0`

```
/odfuzz # odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats -l logs -a
Traceback (most recent call last):
  File "/usr/bin/odfuzz", line 11, in <module>
    load_entry_point('odfuzz==0.13.1', 'console_scripts', 'odfuzz')()
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 23, in main
    execute(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 38, in execute
    set_signal_handler(collection_name)
  File "/usr/lib/python3.6/site-packages/odfuzz-0.13.1-py3.6.egg/odfuzz/odfuzz.py", line 68, in set_signal_handler
    gevent.signal(signal.SIGINT, partial(signal_handler, db_collection_name))
TypeError: 'module' object is not callable
```

Full list of pip packages:
```
/odfuzz # pip list
Package         Version
--------------- ----------
certifi         2020.4.5.1
cffi            1.14.0
chardet         3.0.4
gevent          20.5.0
greenlet        0.4.15
idna            2.9
lxml            4.5.0
odfuzz          0.13.1
pip             20.1
pycparser       2.20
pymongo         3.10.1
pyodata         1.4.0
python-dateutil 2.8.1
PyYAML          5.3.1
requests        2.23.0
setuptools      46.1.3
six             1.14.0
urllib3         1.25.9
```

**Comment by phanak-sap** [comment]
I am NOT ABLE TO REPRODUCE the gevent issue with configuration:

Latest HEAD from master c8bfe9e, Windows environment, clean virtualenv created , `pip install -r requirements.txt`, followed by `pip install -e`  and run odfuzz from virtualenv in CMD:

- requirement.txt containst gevent>=1.2.2
- Python 3.7 in Windows
- Pip somehow (not sure why) grabbedv gevent 1.4.0

Works OK:
```
(v) c:\github-sap-my-forks>odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats
odfuzz version: 0.13.1
Connecting to the database...
Collection: Northwind.svc-c30b331a-13d6-49fc-9404-e3674d29265e
Initializing queryable entities...
```

Full pip list:

```
(v) c:\github-sap-my-forks>pip list
Package            Version
------------------ ---------
astroid            2.3.3
atomicwrites       1.4.0
attrs              19.3.0
bandit             1.6.2
certifi            2019.9.11
cffi               1.13.2
chardet            3.0.4
codecov            2.0.22
colorama           0.4.3
coverage           5.1
gevent             1.4.0
gitdb              4.0.5
GitPython          3.1.2
greenlet           0.4.15
idna               2.8
importlib-metadata 1.6.0
isort              4.3.21
lazy-object-proxy  1.4.3
lxml               4.4.1
mccabe             0.6.1
mongomock          3.19.0
more-itertools     8.2.0
packaging          20.3
pbr                5.4.5
pip                20.1
pluggy             0.13.1
py                 1.8.1
pycparser          2.19
pylint             2.4.4
pymongo            3.9.0
pyodata            1.3.0
pyparsing          2.4.7
pytest             5.4.1
pytest-cov         2.8.1
python-dateutil    2.8.1
PyYAML             5.1.2
requests           2.22.0
sentinels          1.0.0
setuptools         46.1.3
six                1.13.0
smmap              3.0.4
stevedore          1.32.0
typed-ast          1.4.1
urllib3            1.25.7
wcwidth            0.1.9
wheel              0.34.2
wrapt              1.11.2
zipp               3.1.0

```

**Comment by phanak-sap** [comment]
I am ABLE TO REPRODUCE on 

Latest HEAD from master c8bfe9e, Windows environment, clean virtualenv created, modified setup.py to pinned version in first comment in this issue with one previous release of gevent and just  `pip install -e .`, then run odfuzz from virtualenv in CMD:

Python 3.7 in Windows
gevent 20.4.0

```
(v4) c:\github-sap-my-forks\odfuzz>odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats -l logs -a
Traceback (most recent call last):
  File "c:\github-sap-my-forks\odfuzz\v4\Scripts\odfuzz-script.py", line 11, in <module>
    load_entry_point('odfuzz', 'console_scripts', 'odfuzz')()
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 23, in main
    execute(sys.argv[1:])
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 38, in execute
    set_signal_handler(collection_name)
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 68, in set_signal_handler
    gevent.signal(signal.SIGINT, partial(signal_handler, db_collection_name))
TypeError: 'module' object is not callable

(v4) c:\github-sap-my-forks\odfuzz>pip list
Package         Version    Location
--------------- ---------- -----------------------------
certifi         2020.4.5.1
cffi            1.14.0
chardet         3.0.4
gevent          20.4.0
greenlet        0.4.15
idna            2.9
lxml            4.5.0
odfuzz          0.13.1     c:\github-sap-my-forks\odfuzz
pip             20.1
pycparser       2.20
pymongo         3.10.1
pyodata         1.4.0
python-dateutil 2.8.1
PyYAML          5.3.1
requests        2.23.0
setuptools      46.1.3
six             1.14.0
urllib3         1.25.9
wheel           0.34.2


setup.py content

    install_requires=[
        'gevent==20.4.0',
        'requests==2.23.0',
        'pymongo==3.10.1',
        'lxml==4.5.0',
        'pyyaml==5.3.1',
        'python-dateutil==2.8.1',
        'pyodata==1.4.0',
    ],

```

**Comment by phanak-sap** [comment]
I am ABLE TO REPRODUCE on

Latest HEAD from master c8bfe9e, Windows environment, clean virtualenv created, modified setup.py to pinned version in first comment in this issue with selected  release of gevent and just pip install -e ., then run odfuzz from virtualenv in CMD:

- Python 3.7 in Windows
- gevent 1.5.0


```
(v5) c:\github-sap-my-forks\odfuzz>  pip list
Package         Version    Location
--------------- ---------- -----------------------------
certifi         2020.4.5.1
cffi            1.14.0
chardet         3.0.4
gevent          1.5.0
greenlet        0.4.15
idna            2.9
lxml            4.5.0
odfuzz          0.13.1     c:\github-sap-my-forks\odfuzz
pip             20.1
pycparser       2.20
pymongo         3.10.1
pyodata         1.4.0
python-dateutil 2.8.1
PyYAML          5.3.1
requests        2.23.0
setuptools      46.1.3
six             1.14.0
urllib3         1.25.9
wheel           0.34.2

(v5) c:\github-sap-my-forks\odfuzz>odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats -l logs -a
Traceback (most recent call last):
  File "c:\github-sap-my-forks\odfuzz\v5\Scripts\odfuzz-script.py", line 11, in <module>
    load_entry_point('odfuzz', 'console_scripts', 'odfuzz')()
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 23, in main
    execute(sys.argv[1:])
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 38, in execute
    set_signal_handler(collection_name)
  File "c:\github-sap-my-forks\odfuzz\odfuzz\odfuzz.py", line 68, in set_signal_handler
    gevent.signal(signal.SIGINT, partial(signal_handler, db_collection_name))
TypeError: 'module' object is not callable

setup.py content

    install_requires=[
        'gevent==1.5.0',
        'requests==2.23.0',
        'pymongo==3.10.1',
        'lxml==4.5.0',
        'pyyaml==5.3.1',
        'python-dateutil==2.8.1',
        'pyodata==1.4.0',
    ],
```

**Comment by phanak-sap** [comment]
Working correctly on gevent v 1.4.0. This is the last version where the bug does not reproduce. New issue should be created to investigate this behavior since it currently put hard stop on gevent version update.

I used same process as in previous comments, first time i did not reproduce there was unnecessary  requirements.txt   install. 

```
(v6) c:\github-sap-my-forks\odfuzz>pip list
Package         Version    Location
--------------- ---------- -----------------------------
certifi         2020.4.5.1
cffi            1.14.0
chardet         3.0.4
gevent          1.4.0
greenlet        0.4.15
idna            2.9
lxml            4.5.0
odfuzz          0.13.1     c:\github-sap-my-forks\odfuzz
pip             20.1
pycparser       2.20
pymongo         3.10.1
pyodata         1.4.0
python-dateutil 2.8.1
PyYAML          5.3.1
requests        2.23.0
setuptools      46.1.3
six             1.14.0
urllib3         1.25.9
wheel           0.34.2

(v6) c:\github-sap-my-forks\odfuzz>odfuzz https://services.odata.org/V2/Northwind/Northwind.svc/ -s stats -l logs -a
odfuzz version: 0.13.1
Connecting to the database...
Collection: Northwind.svc-7d4cc140-3a17-415a-970c-0f0a14840fa9
Initializing queryable entities...
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
c:\github-sap-my-forks\odfuzz\v6\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'services.odata.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Fuzzing...
Generated tests: 10 | Failed tests: 5 | Raised exceptions: 0
```

**Comment by phanak-sap** [comment]
Since gevent has open dependency  `greenlet >= 0.4.14` I will add pinned dependency in which the odfuzz was tested (`greenlet   0.4.15`) and is working correctly.
